id: ig-fhir-doc-cpage
canonical: https://www.cpage.fr/ig/ig-fhir-doc-cpage
name: IG FHIR Doc CPage
status: draft
version: 0.1.0
date: 2025-12-30
title: Guide documentaire IG FHIR CPage
publisher:
  name: CPage
  url: https://www.cpage.fr
contact:
  - name: CPage
    telecom:
      - system: email
        value: contact@cpage.fr
description: >-
  Ce guide propose une documentation complète sur la création, la publication et la maintenance des guides d’implémentation FHIR, à destination de la communauté de l’entreprise.
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
  shownav: true

dependencies: {}

pages:
  index.md:
    title: Accueil
  quickstart.md:
    title: Prise en main rapide
  installation.md:
    title: Installation de l’environnement
  structure-et-organisation.md:
    title: Structure et organisation
  methodologie-outils-publication.md:
    title: Méthodologie, outils, publication
  profiles.md:
    title: Profils FHIR
  extensions.md:
    title: Extensions FHIR
  terminologies.md:
    title: Terminologies FHIR
  packages.md:
    title: Utiliser les packages IG
  integration-package.md:
    title: Intégration package IG
  faq.md:
    title: FAQ
  bonnes-pratiques.md:
    title: Bonnes pratiques
  liens-utiles.md:
    title: Liens utiles
  annexes.md:
    title: Annexes

menu:
  "Accueil": index.html
  "Guide de démarrage":
    "Prise en main rapide": quickstart.html
    "Installation de l’environnement": installation.html
    "Structure et organisation": structure-et-organisation.html
    "Méthodologie, outils, publication": methodologie-outils-publication.html
    "Bonnes pratiques": bonnes-pratiques.html
  "Ressources normatives":
    "Profils FHIR": profiles.html
    "Extensions FHIR": extensions.html
    "Terminologies FHIR": terminologies.html
  "Distribution":
    "Utiliser les packages IG": packages.html
    "Intégration package IG": integration-package.html
  "Aide & Annexes":
    "FAQ": faq.html
    "Liens utiles": liens-utiles.html
    "Annexes": annexes.html